export const GET_HOTELS_SUCCESSFUL = "GET HOTELS SUCCESSFUL";
export const GET_HOTELS_FAIL = "GET HOTELS FAIL";
export const GET_HOTELS_LOADING = "GET HOTELS LOADING";

export const CREATE_HOTELS_SUCCESSFUL = "CREATE_HOTELS_SUCCESSFUL";
export const CREATE_HOTELS_LOADING = "CREATE_HOTELS_LOADING";
export const CREATE_HOTELS_FAIL = "CREATE_HOTELS_FAIL";

export const EDIT_HOTELS_SUCCESSFUL = "EDIT_HOTELS_SUCCESSFUL";
export const EDIT_HOTELS_LOADING = "EDIT_HOTELS_LOADING";
export const EDIT_HOTELS_FAIL = "EDIT_HOTELS_FAIL";

export const DELETE_HOTELS_SUCCESSFUL = "DELETE_HOTELS_SUCCESSFUL";
export const DELETE_HOTELS_FAIL = "DELETE_HOTELS_FAIL";
export const DELETE_HOTELS_LOADING = "DELETE_HOTELS_LOADING";
